name: deopay
description: A Flutter frontend for Deopay - minimal scaffold created by assistant
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.7
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logof.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/coin.svg
    - assets/images/character.svg
    - assets/videos/Intro.mp4
