name: smart_wallet
description: A Flutter frontend for SmartWallet - Osiris117
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.7
  video_player: ^2.6.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/coin.svg
    - assets/images/character.svg
    - assets/videos/Intro.mp4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logof.png"
